CREATE USER bookshare IDENTIFIED BY manager;

GRANT CONNECT, RESOURCE TO bookshare;
GRANT CREATE SESSION TO bookshare;
GRANT UNLIMITED TABLESPACE TO bookshare; 
GRANT EXECUTE ON MDSYS.SDO_GEOM TO bookshare;

COMMIT;
